import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { readFile, readdir } from "node:fs/promises";
import { spawnSync } from "node:child_process";

const manifest = JSON.parse(await readFile("package.json", "utf8"));
const lock = JSON.parse(await readFile("package-lock.json", "utf8"));
const license = await readFile("LICENSE", "utf8");
const notice = await readFile("NOTICE", "utf8");
const trademarks = await readFile("TRADEMARKS.md", "utf8");
const thirdParty = await readFile("THIRD_PARTY_NOTICES.md", "utf8");

assert.deepEqual(manifest.repository, {
  type: "git",
  url: "git+https://github.com/tetracoralla/Gridlace.git",
});
assert.equal(manifest.homepage, "https://github.com/tetracoralla/Gridlace#readme");
assert.equal(manifest.bugs?.url, "https://github.com/tetracoralla/Gridlace/issues");

const tracked = spawnSync("git", ["ls-files", "-z"], { encoding: "utf8" });
assert.equal(tracked.status, 0, tracked.stderr || "git ls-files failed");
const trackedFiles = tracked.stdout.split("\0").filter(Boolean);
const forbiddenTrackedPaths = [
  /(^|\/)\.DS_Store$/u,
  /(^|\/)\.env(?:\.|$)/u,
  /(^|\/)(?:coverage|dist|node_modules|test-results|ui-dist)(?:\/|$)/u,
  /\.(?:bak|log|orig|patch|rej|tgz|zip)$/iu,
];
for (const path of trackedFiles) {
  assert.equal(
    forbiddenTrackedPaths.some((pattern) => pattern.test(path)),
    false,
    `temporary or generated artifact must not be tracked: ${path}`,
  );
}

const trackedModes = spawnSync("git", ["ls-files", "-s", "-z"], { encoding: "utf8" });
assert.equal(trackedModes.status, 0, trackedModes.stderr || "git ls-files -s failed");
assert.equal(
  trackedModes.stdout.split("\0").filter(Boolean).some((entry) => entry.startsWith("120000 ")),
  false,
  "public source must not contain tracked symlinks",
);

const rasterAssets = trackedFiles.filter((path) => /\.(?:gif|jpe?g|png|webp)$/iu.test(path)).sort();
assert.deepEqual(rasterAssets, ["design/gridlace-concept.png"], "review every tracked raster asset explicitly");

const oldIdentityPatterns = [
  new RegExp(["Cat", "s Cradle"].join("[’']?"), "iu"),
  new RegExp(["cats", "cradle"].join("-"), "iu"),
  new RegExp(["dependency", "engine", "concept"].join("-"), "iu"),
];
const sourceTracePatterns = [
  new RegExp(`Generated by (?:${["Codex", "ChatGPT", "Claude"].join("|")})`, "iu"),
  /\bagent[-_ ]?(?:session|trace)\b/iu,
];
const localPathPatterns = [
  /\/Users\/[^/\s]+\//u,
  /\/home\/[^/\s]+\//u,
  /C:\\Users\\[^\\\s]+\\/iu,
  /file:\/\//iu,
];
const secretPatterns = [
  /-----BEGIN (?:RSA |OPENSSH |EC )?PRIVATE KEY-----/u,
  new RegExp(`\\bgh(?:${["p", "o", "u", "s", "r"].join("|")})_[A-Za-z0-9_]{20,}\\b`, "u"),
  new RegExp(`\\b${["github", "pat"].join("_")}_[A-Za-z0-9_]{20,}\\b`, "iu"),
  new RegExp(`\\b${["s", "k"].join("")}-(?:proj-)?[A-Za-z0-9_-]{20,}\\b`, "u"),
  /\bAKIA[0-9A-Z]{16}\b/u,
  /\b(?:OPENAI_API_KEY|ANTHROPIC_API_KEY|AWS_SECRET_ACCESS_KEY)\s*[:=]\s*["']?[A-Za-z0-9_/+=.-]{12,}/u,
];
for (const path of trackedFiles) {
  const content = await readFile(path);
  if (content.includes(0)) continue;
  const text = content.toString("utf8");
  for (const [category, patterns] of [
    ["old product identity", oldIdentityPatterns],
    ["local absolute path", localPathPatterns],
    ["likely secret", secretPatterns],
    ["generated Agent work trace", sourceTracePatterns],
  ]) {
    assert.equal(
      patterns.some((pattern) => pattern.test(text)),
      false,
      `${category} found in tracked text: ${path}`,
    );
  }
}

const reachableHistory = spawnSync(
  "git",
  ["log", "--format=%B", "-p", "--no-ext-diff", "HEAD"],
  { encoding: "utf8", maxBuffer: 64 * 1024 * 1024 },
);
assert.equal(reachableHistory.status, 0, reachableHistory.stderr || "git history scan failed");
for (const [category, patterns] of [
  ["old product identity", oldIdentityPatterns],
  ["local absolute path", localPathPatterns],
  ["likely secret", secretPatterns],
  ["generated Agent work trace", sourceTracePatterns],
]) {
  assert.equal(
    patterns.some((pattern) => pattern.test(reachableHistory.stdout)),
    false,
    `${category} found in reachable Git history`,
  );
}

// SHA-256 of the unmodified Apache License 2.0 text from apache.org/licenses/LICENSE-2.0.txt.
assert.equal(
  createHash("sha256").update(license).digest("hex"),
  "cfc7749b96f63bd31c3c42b5c471bf756814053e847c10f3eb003417bc523d30",
  "LICENSE must remain the official Apache License 2.0 text",
);
assert.match(notice, /Copyright 2026 openAdam/u);
assert.match(notice, /^Gridlace$/mu);
assert.match(trademarks, /Gridlace/u);
assert.match(trademarks, /openAdam/u);
assert.match(
  trademarks,
  /does not grant\s+permission to use trade names, trademarks, service marks, or product names/u,
);
function usesForbiddenRegistry(value) {
  if (typeof value !== "string") return false;
  try {
    const host = new URL(value).hostname.toLowerCase();
    return host === "npmmirror.com" || host.endsWith(".npmmirror.com");
  } catch {
    return false;
  }
}

assert.equal(usesForbiddenRegistry("https://registry.npmmirror.com/example/-/example.tgz"), true);
assert.equal(usesForbiddenRegistry("https://registry.npmjs.org/example?next=registry.npmmirror.com"), false);
for (const [path, entry] of Object.entries(lock.packages)) {
  assert.equal(
    usesForbiddenRegistry(entry.resolved),
    false,
    `the public lockfile must not resolve ${path || "the root package"} through a workstation-specific mirror`,
  );
}

for (const required of ["LICENSE", "NOTICE", "TRADEMARKS.md", "THIRD_PARTY_NOTICES.md", "SECURITY.md", "CONTRIBUTING.md"]) {
  assert.equal(manifest.files.includes(required), true, `${required} must be declared in package files`);
}

const bundledPackages = [
  ["React", manifest.dependencies.react],
  ["React DOM", manifest.dependencies["react-dom"]],
  ["Scheduler", lock.packages["node_modules/scheduler"].version],
  ["Zod", manifest.dependencies.zod],
  ["@noble/hashes", manifest.dependencies["@noble/hashes"]],
];
for (const [name, version] of bundledPackages) {
  assert.equal(thirdParty.includes(`${name} ${version}`), true, `${name} ${version} needs a bundled notice`);
}
for (const dependencyLicense of [
  "node_modules/react/LICENSE",
  "node_modules/react-dom/LICENSE",
  "node_modules/scheduler/LICENSE",
  "node_modules/zod/LICENSE",
  "node_modules/@noble/hashes/LICENSE",
]) {
  const text = (await readFile(dependencyLicense, "utf8")).trim();
  assert.equal(thirdParty.includes(text), true, `${dependencyLicense} must be reproduced verbatim`);
}

const browserAssets = await readdir("ui-dist/assets");
assert.equal(browserAssets.some((file) => file.endsWith(".js")), true, "the browser bundle must be built before release checks");
const browserLegalSources = {
  LICENSE: license,
  NOTICE: notice,
  "TRADEMARKS.md": trademarks,
  "THIRD_PARTY_NOTICES.md": thirdParty,
};
for (const [required, source] of Object.entries(browserLegalSources)) {
  const bundledCopy = await readFile(`ui-dist/${required}`, "utf8");
  assert.equal(bundledCopy, source, `${required} must accompany the standalone browser bundle`);
}

const packed = spawnSync("npm", ["pack", "--dry-run", "--json", "--ignore-scripts"], {
  encoding: "utf8",
  env: { ...process.env, npm_config_update_notifier: "false" },
});
assert.equal(packed.status, 0, packed.stderr || "npm pack --dry-run failed");
const report = JSON.parse(packed.stdout);
assert.equal(report.length, 1, "npm pack must produce one package report");
const packedFiles = new Set(report[0].files.map((entry) => entry.path));
for (const required of ["LICENSE", "NOTICE", "TRADEMARKS.md", "THIRD_PARTY_NOTICES.md", "SECURITY.md", "CONTRIBUTING.md"]) {
  assert.equal(packedFiles.has(required), true, `${required} is missing from the npm package`);
}

process.stdout.write("Release hygiene checks passed.\n");
